### ISSUE TITLE
README.md inconsistencies with safe_ffi

### ISSUE THREAD

**Issue by happybeing** [maidsafe/safe_firefox_addon#8]
README.md:

> Copy the libc_wrapper.{so, dylib} from the target/release folder to the data folder of the Safe-Addon

Two issues here:
- the space before "dylib" causes an error
- there is no "libc_wrapper._" or "_.dylib". Building safe_ffi creates: libsafe_ffi.{.a,.so.rlib}

**Comment by Viv-Rajkumar** [comment]
Think README is indeed out of date here. Should be [updated now](https://github.com/maidsafe/safe_firefox_addon/commit/3c0cc042c8938ad9b267149133e5843af573a57c). Looks like in [code](https://github.com/maidsafe/safe_firefox_addon/blob/master/proto_handler.js#L50) we were looking for the right file, but readme had a different name specified for the dependency.

> the space before "dylib" causes an error

that was not meant to have a space. it was just to indicate you needed either the .so or the .dylib file depending on if you're using Linux/OSX. hopefully the updated README should make it a bit more clear

> there is no "libc_wrapper." or ".dylib". Building safe_ffi creates: libsafe_ffi.{.a,.so.rlib}

This is now fixed. it should indeed be `libsafe_ffi` and not `libc_wrapper`. You'll need the dynamic library which is the `.so` for you in linux.
